apiVersion: v2
name: websight-cms
description: This chart bootstraps WebSight CMS deployment on a Kubernetes cluster using the Helm package manager.
type: application
version: 2.0.0
appVersion: "1.22.1"

dependencies:
  - name: mongodb
    version: 14.3.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: mongodb.enabled