# Default values for websight-cms.
# This is a YAML-formatted file.

# WebSight CMS configuration
cms:
  image: 
    # -- project image repository
    repository: europe-docker.pkg.dev/websight-io/public/websight-cms-starter
    # -- project image tag, overwrites value from `.Chart.appVersion`
    tag:
    # -- project image pull policy
    pullPolicy: IfNotPresent
  # -- cms image pull secrets
  imagePullSecrets: []
  persistence:  
    # -- sets persistence mode, currenly `tar` is the only supported mode
    mode: tar
    tar:
      # -- tar persistance volume size
      size: 2Gi
      # -- tar persistance volume storage class
      storageClassName: ""
  # -- environment variables
  env: []
  # -- List of secrets that will work with `secretRef`
  envsFromSecret: []
  # -- List of config maps that will work with `configMapRef`
  envsFromConfig: []
  # -- Name of the secret (without release name prefix) where custom admin password is stored under `WS_ADMIN_PASSWORD` key
  customAdminSecret:
  # -- container's resources settings
  resources:
    # @ignored in generated docs
    requests:
      cpu: 500m
      memory: 1Gi
  livenessProbe:
    # -- enables pods liveness probe
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
    successThreshold: 1
  readinessProbe:
    # -- enables pods readiness probe
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 3
    successThreshold: 1
  # -- (object) node selector
  nodeSelector:
  debug:
    # -- enables debug on port 5005
    enabled: false

# Ingress configuration for local development
ingress:
  # -- enables ingress
  enabled: false
  # -- custom ingress annotations
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 5m
  hosts:
    # -- cms host
    cms: "cms.127.0.0.1.nip.io"
