# Default values for websight-cms.
# This is a YAML-formatted file.

# WebSight CMS configuration
cms:
  image: 
    # -- project image repository
    repository: europe-docker.pkg.dev/websight-io/public/websight-cms-starter
    # -- project image tag, overwrites value from `.Chart.appVersion`
    tag:
    # -- project image pull policy
    pullPolicy: IfNotPresent
  # -- cms image pull secrets
  imagePullSecrets: []
  # -- number of replicas, mind that `tar` persistence mode will create a StatefulSet, while `mongo` will create a Deployment
  replicas: 1
  # -- update strategy, works only for `mongo` persistence mode
  updateStrategy: {}
  persistence:  
    # -- sets persistence mode, possible options are `tar` or `mongo`
    mode: tar
    # tar persistance settings, applied only when persistance is set to `tar`
    tar:
      # -- tar persistance volume size
      size: 2Gi
      # -- tar persistance volume storage class
      storageClassName: ""
    # mongo persistance settings, applied only when persistance is set to `mongo`, available since CMS version 1.23.0+
    mongo:
      # -- comma separated list of [mongo hosts](https://www.mongodb.com/docs/manual/reference/connection-string/#standard-connection-string-format)
      hosts: mongodb:27017
      # -- mongo connection options
      connectionOptions: ""
      # -- mongo admin username
      username: "mongoadmin"
      # -- secret name where mongo admin password is stored under `oak.doc.ns.mongouri.password` key, if not set, default "mongoadmin" password will be used
      passwordSecret:
  # -- environment variables
  env: []
  # -- List of secrets that will work with `secretRef`
  envsFromSecret: []
  # -- List of config maps that will work with `configMapRef`
  envsFromConfig: []
  # -- Name of the secret (without release name prefix) where custom admin password is stored under `WS_ADMIN_PASSWORD` key
  customAdminSecret:
  # -- container's resources settings
  resources:
    # @ignored in generated docs
    requests:
      cpu: 500m
      memory: 1Gi
  livenessProbe:
    # -- enables pods liveness probe
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
    successThreshold: 1
  readinessProbe:
    # -- enables pods readiness probe
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 3
    successThreshold: 1
  # -- (object) node selector
  nodeSelector:
  debug:
    # -- enables debug on port 5005
    enabled: false
  ingress:
    # -- enables CMS ingress
    enabled: false
    # -- ingress class name
    ingressClassName: nginx
    # -- custom CMS ingress annotations
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 5m
    # -- cms host
    host:
    tls:
      # -- defines the secret name for the TLS certificate, if set, the TLS will be enabled
      secretName:
    session:
      # -- nginx ingress affinity settings
      cookie:
        expires: 172800
        maxAge: 172800

# WebSight CMS proxy configuration
proxy:
  # -- enables proxy
  enabled: false
  # -- proxy image repository
  image:
    repository: nginx
    tag: stable-alpine
  # -- proxy image pull secrets
  imagePullSecrets: []
  # -- number of replicas
  replicas: 1
  # -- update strategy
  updateStrategy: {}
  # -- container's resources settings
  resources:
    # @ignored in generated docs
    requests:
      cpu: 50m
      memory: 50Mi
  # -- environment variables
  env: []
  # -- (object) liveliness probe config
  livenessProbe:
    # -- enables pods liveness probe
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
  # -- (object) readiness probe config
  readinessProbe:
    # -- enables pods readiness probe
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
  # -- (object) node selector
  nodeSelector:
  ingress:
    # -- ingress class name
    ingressClassName: nginx
    # -- custom ingress annotations
    annotations: {}
  # -- (object) site configuration, see the `examples/luna-proxy` for more details
  sites: []
