# Default values for websight-cms.
# This is a YAML-formatted file.

# WebSight CMS configuration
cms:
  ports:
    # -- CMS Panel port
    panel: 8080
  image: 
    # -- WebSight CMS project image repository
    repository: public.ecr.aws/ds/websight-cms-starter
    # -- WebSight CMS project image tag
    tag: 1.6.0
    # -- WebSight CMS project image pull policy
    pullPolicy: IfNotPresent
  # -- number of WebSight CMS replicas
  replicas: 1
  # -- WebSight CMS environment variables
  env:
    - name: LEASE_CHECK_MODE
      value: LENIENT
  # -- List of WebSight CMS secrets that will work with `secretRef`
  envsFromSecret: []
  # -- List of WebSight CMS config maps that will work with `configMapRef`
  envsFromConfig: []
  # -- Name of the secret (without release name prefix) where custom admin password is stored under `WS_ADMIN_PASSWORD` key
  customAdminSecret:
  resources:
    requests:
      # -- WebSight CMS request memory resources
      memory: 1Gi
      # -- WebSight CMS request cpu resources
      cpu: 500m
    limits:
      # -- WebSight CMS limits memory resources
      memory: 4Gi
      # -- WebSight CMS limits cpu resources
      cpu: 1000m
  livenessProbe:
    # -- enables WebSight CMS pods liveness probe
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
    successThreshold: 1
  readinessProbe:
    # -- enables WebSight CMS pods readiness probe
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 3
    successThreshold: 1

# Web Server (Nginx) configuration
nginx:
  # -- enables Web Server
  enabled: true
  ports:
    # -- Nginx port
    http: 80
  image: 
    # -- Web Server image repository
    repository: public.ecr.aws/ds/websight-nginx-starter
    # -- Web Server project image tag
    tag: 1.6.0
    # -- Web Server image pull policy
    pullPolicy: IfNotPresent
  # -- number of Web Server replicas
  replicas: 2
  # -- WebSight Nginx environment variables
  env: []
  resources:
    requests:
      # -- WebSight Nginx request memory resources
      memory: 50Mi
      # -- WebSight Nginx request cpu resources
      cpu: 50m
    limits:
      # -- WebSight Nginx limits memory resources
      memory: 100Mi
      # -- WebSight Nginx limits cpu resources
      cpu: 100m
  livenessProbe:
    # -- enables WebSight Nginx pods liveness probe
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 5
    timeoutSeconds: 1
    failureThreshold: 6
    successThreshold: 1

# Site Repository volume configuration
siteRepository:
  # -- enables Site Repository volume
  enabled: true
  storage:
    # -- Site Repository volume size
    size: 2Gi
  # -- (string) Configure storageClassName in case you want to use `ReadWriteMany` access mode
  rwxStorageClassName:
# MongoDB Content Store configuration
mongo:
  ports:
    # -- MongoDB Content Store port
    service: 27017
  image: 
    # -- MongoDB Content Store image repository
    repository: mongo
    # -- MongoDB Content Store image tag
    tag: 4.4.6
    # -- MongoDB Content Store image pull policy
    pullPolicy: IfNotPresent
  # -- MongoDB Content Store environment variables
  env:
    - name: MONGO_INITDB_ROOT_PASSWORD
      value: mongoadmin
    - name: MONGO_INITDB_ROOT_USERNAME
      value: mongoadmin
  resources:
    requests:
      # -- MongoDB request memory resources
      memory: 1Gi
      # -- MongoDB request cpu resources
      cpu: 500m
    limits:
      # -- MongoDB limits memory resources
      memory: 4Gi
      # -- MongoDB limits cpu resources
      cpu: 1000m
  livenessProbe:
    # -- enables MongoDB pods liveness probe
    enabled: true
    initialDelaySeconds: 15
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  storage:
    # -- MongoDB Repository volume size
    size: 2Gi

# Ingress configuration
ingress:
  # -- enables ingress
  enabled: false
  hosts:
    # -- cms panel host
    cms: "cms.127.0.0.1.nip.io"
    # -- demo sites hosts
    sites: 
      - "luna.127.0.0.1.nip.io"
      - "bulma-personal-template.127.0.0.1.nip.io"
      - "no-code.luna.127.0.0.1.nip.io"