{{- if .Values.cms.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.cms.serviceAccount.name | default (include "websight-cms.component.fullname" (dict "componentName" "cms" "context" $)) }}
  labels:
    {{- include "websight-cms.component.labels" (dict "componentName" "cms" "context" $) | nindent 4 }}
automountServiceAccountToken: {{ .Values.cms.serviceAccount.automountServiceAccountToken }}
{{- end }}