apiVersion: v1
kind: Service
metadata:
  name: {{ include "websight-cms.fullname" . }}
  labels:
    {{- include "websight-cms.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: panel
      port: 8080
      targetPort: 8080
  selector:
    {{- include "websight-cms.selectorLabels" . | nindent 4 }}
