{{- if .Values.cms.ingress.enabled -}}
{{- with .Values.cms.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "websight-cms.component.fullname" (dict "componentName" "cms" "context" $) }}
  annotations:
    {{- if gt ($.Values.cms.replicas | int) 1 }}
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "websight-cms-sticky"
    nginx.ingress.kubernetes.io/session-cookie-expires: {{ .session.cookie.expires | quote }}
    nginx.ingress.kubernetes.io/session-cookie-max-age: {{ .session.cookie.maxAge | quote }}
    {{- end }}
    {{- if .annotations }}
    {{- .annotations | toYaml | nindent 4 }}
    {{- end }}
  labels:
    {{- include "websight-cms.component.labels" (dict "componentName" "cms" "context" $) | nindent 4 }}
spec:
  ingressClassName: {{ .ingressClassName }}
  {{- if (.tls).secretName }}
  tls:
    - hosts:
        - {{ tpl .host $ }}
      secretName: {{ .tls.secretName }}
  {{- end }}
  rules:
  - host: {{ tpl .host $ }}
    http:
      paths:
      - pathType: ImplementationSpecific
        path: "/"
        backend:
          service:
            name: {{ include "websight-cms.component.fullname" (dict "componentName" "cms" "context" $) }}
            port:
              number: 8080
{{- end }}
{{- end }}