{{- if .Values.cms.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "websight-cms.component.fullname" (dict "componentName" "cms" "context" $) }}
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- if gt .Values.cms.replicas 1 }}
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "websight-cms-sticky"
    nginx.ingress.kubernetes.io/session-cookie-expires: {{ .Values.cms.session.cookie.expires | quote }}
    nginx.ingress.kubernetes.io/session-cookie-max-age: {{ .Values.cms.session.cookie.maxAge | quote }}
    {{- end }}
    {{- if .Values.cms.ingress.annotations }}
    annotations: {{- .Values.cms.ingress.annotations | toYaml | nindent 4 }}
    {{- end }}
  labels:
    {{- include "websight-cms.component.labels" (dict "componentName" "cms" "context" $) | nindent 4 }}
spec:
  rules:
  - host: {{ tpl .Values.cms.ingress.host . }}
    http:
      paths:
      - pathType: ImplementationSpecific
        path: "/"
        backend:
          service:
            name: {{ include "websight-cms.component.fullname" (dict "componentName" "cms" "context" $) }}
            port:
              number: 8080
{{- end }}