apiVersion: v1
kind: Service
metadata:
  name: {{ include "websight-cms.component.fullname" (dict "componentName" "cms" "context" $) }}
  labels:
    {{- include "websight-cms.component.labels" (dict "componentName" "cms" "context" $) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: panel
      port: 8080
      targetPort: 8080
  selector:
    {{- include "websight-cms.component.selectorLabels" (dict "componentName" "cms" "context" $) | nindent 4 }}
