apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "websight-cms.fullname" . }}-cms
  labels:
    app.kubernetes.io/name: {{ include "websight-cms.name" . }}-cms
    app.kubernetes.io/instance: {{ .Release.Name }}-cms
    app.kubernetes.io/version: {{ .Values.cms.image.tag }}
    app.kubernetes.io/websight-version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: cms
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.cms.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "websight-cms.name" . }}-cms
      app.kubernetes.io/instance: {{ .Release.Name }}-cms
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "websight-cms.name" . }}-cms
        app.kubernetes.io/instance: {{ .Release.Name }}-cms
    spec:
      containers:
        - name: cms
          image: "{{ .Values.cms.image.repository }}:{{ .Values.cms.image.tag }}"
          imagePullPolicy: {{ .Values.cms.image.pullPolicy }}
          env:
            - name: MONGODB_HOST
              value: {{ include "websight-cms.fullname" . }}-mongo
            - name: MONGODB_PORT
              value: "27017"
            {{- range $k, $v := .Values.cms.env }}
            - name: {{ $v.name }}
              value: {{ $v.value | quote }}
            {{- end }}
            {{- if .Values.cms.debug.enabled }}
            - name: WS_DEBUG
              value: "true"
            {{- end }}
          envFrom:
          {{- range .Values.cms.envsFromSecret }}
          - secretRef:
              name: {{ $.Release.Name }}-{{ . }}
          {{- end }}
          {{- range .Values.cms.envsFromConfig }}
          - configMapRef:
              name: {{ $.Release.Name }}-{{ . }}
          {{- end }}
          ports:
            - name: panel
              containerPort: 8080
            {{- if .Values.cms.debug.enabled }}
            - name: debug
              containerPort: 5005
            {{- end }}
          resources:
            requests:
              memory: {{ .Values.cms.resources.requests.memory }}
              cpu: {{ .Values.cms.resources.requests.cpu }}
            limits:
              memory: {{ .Values.cms.resources.limits.memory }}
              cpu: {{ .Values.cms.resources.limits.cpu }}
          volumeMounts:
          {{- if .Values.cms.customAdminSecret }}
            - name: admin-password
              mountPath: /websight/resources/secrets
              readOnly: true
          {{- end }}
          {{- if .Values.siteRepository.enabled }}
            - mountPath: /websight/docroot
              name: site-repository
          {{- end }}
          {{- if .Values.cms.livenessProbe.enabled }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.cms.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.cms.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.cms.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.cms.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.cms.livenessProbe.successThreshold }}
            httpGet:
              path: /system/health
              port: 8080
              scheme: HTTP
          {{- end }}
          {{- if .Values.cms.readinessProbe.enabled }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.cms.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.cms.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.cms.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.cms.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.cms.readinessProbe.successThreshold }}
            httpGet:
              path: /apps/websight-authentication/login.html
              port: 8080
              scheme: HTTP
          {{- end }}
      restartPolicy: Always
      volumes:
      {{- if .Values.siteRepository.enabled }}
        - name: site-repository
          persistentVolumeClaim:
            claimName: {{ include "websight-cms.fullname" . }}-site-repository
      {{- end }}
      {{- if .Values.cms.customAdminSecret }}
        - name: admin-password
          secret:
            secretName: {{ $.Release.Name }}-{{ .Values.cms.customAdminSecret }}
            items:
              - key: WS_ADMIN_PASSWORD
                path: admin.password
      {{- end }}
      {{- if .Values.cms.nodeSelector }}
      nodeSelector: {{- .Values.cms.nodeSelector | toYaml | nindent 8 }}
      {{- end }}
status: {}
