{{- if .Values.proxy.enabled -}}
{{- if .Values.proxy.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.proxy.serviceAccount.name | default (include "websight-cms.component.fullname" (dict "componentName" "proxy" "context" $)) }}
  labels:
    {{- include "websight-cms.component.labels" (dict "componentName" "proxy" "context" $) | nindent 4 }}
automountServiceAccountToken: {{ .Values.proxy.serviceAccount.automountServiceAccountToken }}
{{- end }}
{{- end }}