# Default values for websight-ce.
# This is a YAML-formatted file.

# WebSight CMS CE configuration
cms:
  ports:
    # -- CMS Panel port
    panel: 8080
  image: 
    # -- WebSight CMS CE project image repository
    repository: public.ecr.aws/ds/websight-cms-ce
    # -- WebSight CMS CE project image tag
    tag: luna-2.1.1
  # -- number of WebSight CMS CE replicas
  replicas: 1
  resources:
    requests:
      # -- WebSight CMS CE request memory resources
      memory: 1Gi
      # -- WebSight CMS CE request cpu resources
      cpu: 500m
    limits:
      # -- WebSight CMS CE limits memory resources
      memory: 4Gi
      # -- WebSight CMS CE limits cpu resources
      cpu: 1000m
  livenessProbe:
    # -- enables WebSight CMS CE pods liveness probe
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
    successThreshold: 1
  readinessProbe:
    # -- enables WebSight CMS CE pods readiness probe
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 3
    successThreshold: 1

# Web Server (Nginx) configuration
nginx:
  ports:
    # -- Nginx port
    http: 80
  image: 
    # -- Web Server image repository
    repository: public.ecr.aws/ds/websight-nginx-ce
    # -- Web Server project image tag
    tag: luna-2.1.1
  # -- number of Web Server replicas
  replicas: 2
  resources:
    requests:
      # -- WebSight Nginx request memory resources
      memory: 50Mi
      # -- WebSight Nginx request cpu resources
      cpu: 50m
    limits:
      # -- WebSight Nginx limits memory resources
      memory: 100Mi
      # -- WebSight Nginx limits cpu resources
      cpu: 100m
  livenessProbe:
    # -- enables WebSight Nginx pods liveness probe
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 5
    timeoutSeconds: 1
    failureThreshold: 6
    successThreshold: 1

# Site Repository volume configuration
siteRepository:
  storage:
    # -- Site Repository volume size
    size: 2Gi
  # -- (string) Configure storageClassName in case you want to use `ReadWriteMany` access mode
  rwxStorageClassName:
# MongoDB Content Store configuration
mongo:
  ports:
    # -- MongoDB Content Store port
    service: 27017
  image: 
    # -- MongoDB Content Store image repository
    repository: mongo
    # -- MongoDB Content Store image tag
    tag: 4.4.6
  resources:
    requests:
      # -- MongoDB request memory resources
      memory: 1Gi
      # -- MongoDB request cpu resources
      cpu: 500m
    limits:
      # -- MongoDB limits memory resources
      memory: 4Gi
      # -- MongoDB limits cpu resources
      cpu: 1000m
  livenessProbe:
    # -- enables MongoDB pods liveness probe
    enabled: true
    initialDelaySeconds: 15
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  storage:
    # -- MongoDB Repository volume size
    size: 2Gi

# Ingress configuration
ingress:
  # -- enables ingress
  enabled: false
  hosts:
    # -- cms panel host
    cms: "cms.127.0.0.1.nip.io"
    # -- site host
    site: "luna.127.0.0.1.nip.io"
