{{- if .Values.nginx.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "websight-cms.fullname" . }}-nginx
  labels:
    app.kubernetes.io/name: {{ include "websight-cms.name" . }}-nginx
    app.kubernetes.io/instance: {{ .Release.Name }}-nginx
    app.kubernetes.io/version: {{ .Values.nginx.image.tag }}
    app.kubernetes.io/websight-version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: "web-server"
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.nginx.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "websight-cms.name" . }}-nginx
      app.kubernetes.io/instance: {{ .Release.Name }}-nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "websight-cms.name" . }}-nginx
        app.kubernetes.io/instance: {{ .Release.Name }}-nginx
    spec:
      containers:
        - image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          name: nginx
          env:
            {{- range $k, $v := .Values.nginx.env }}
            - name: {{ $v.name }}
              value: {{ $v.value | quote }}
            {{- end }}
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: {{ .Values.nginx.resources.requests.memory }}
              cpu: {{ .Values.nginx.resources.requests.cpu }}
            limits:
              memory: {{ .Values.nginx.resources.limits.memory }}
              cpu: {{ .Values.nginx.resources.limits.cpu }}
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: site-repository
              readOnly: true
            - name: nginx-config
              mountPath: "/etc/nginx/conf.d"
              readOnly: true
          {{- if .Values.nginx.livenessProbe.enabled }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.nginx.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.nginx.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.nginx.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.nginx.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.nginx.livenessProbe.successThreshold }}
            httpGet:
              path: /health
              port: 80
              scheme: HTTP
          {{- end }}

      restartPolicy: Always
      volumes:
        - name: site-repository
          persistentVolumeClaim:
            claimName: {{ include "websight-cms.fullname" . }}-site-repository
            readOnly: true
        - name: nginx-config
          projected:
            sources:
              {{- range .Values.nginx.customServerConfigurations }}
              - configMap:
                  name: {{ .configMapName }}
                  items:
{{ toYaml .configNames | indent 20 }}
              {{- end }}
      {{- if .Values.nginx.nodeSelector }}
      nodeSelector: {{- .Values.nginx.nodeSelector | toYaml | nindent 8 }}
      {{- end }}
{{- end }}