{{- if .Values.nginx.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "websight-cms.fullname" . }}-nginx
  labels:
    app.kubernetes.io/name: {{ include "websight-cms.name" . }}-nginx
    app.kubernetes.io/instance: {{ .Release.Name }}-nginx
    app.kubernetes.io/version: {{ .Values.nginx.image.tag }}
    app.kubernetes.io/websight-version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: "web-server"
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - port: {{ .Values.nginx.ports.http }}
      targetPort: 80
  selector:
    app.kubernetes.io/name: {{ include "websight-cms.name" . }}-nginx
    app.kubernetes.io/instance: {{ .Release.Name }}-nginx
{{- end }}