{{- if .Values.nginx.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "websight-cms.name" . }}-default-configs
  labels:
    app.kubernetes.io/name: {{ include "websight-cms.name" . }}-nginx
    app.kubernetes.io/instance: {{ .Release.Name }}-nginx
    app.kubernetes.io/version: {{ .Values.nginx.image.tag }}
    app.kubernetes.io/websight-version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: "web-server"
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  healthcheck.conf: |-
    server {
        listen       80 default_server;
        server_name  _;
  
        location /health {
            access_log off;
            add_header  Content-Type    text/html;
            return 200;
        }
    }
  10-include-tmp.conf: |-
    include /tmp/nginx/conf.d/*;
{{- end }}