apiVersion: v1
kind: Service
metadata:
  name: {{ include "websight-ce.fullname" . }}-cms
  labels:
    app.kubernetes.io/name: {{ include "websight-ce.name" . }}-cms
    app.kubernetes.io/instance: {{ .Release.Name }}-cms
    app.kubernetes.io/version: {{ .Values.cms.image.tag }}
    app.kubernetes.io/websight-version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: cms
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.cms.ports.panel }}
      targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ include "websight-ce.name" . }}-cms
    app.kubernetes.io/instance: {{ .Release.Name }}-cms
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.cms.sessionAffinityTimeout }}
