apiVersion: v1
kind: Service
metadata:
  name: {{ include "websight-cms.fullname" . }}-mongo
  labels:
    app.kubernetes.io/name: {{ include "websight-cms.name" . }}-mongo
    app.kubernetes.io/instance: {{ .Release.Name }}-mongo
    app.kubernetes.io/version: {{ .Values.mongo.image.tag }}
    app.kubernetes.io/websight-version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: "content-store"
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - port: {{ .Values.mongo.ports.service }}
      targetPort: 27017
  selector:
    app.kubernetes.io/name: {{ include "websight-cms.name" . }}-mongo
    app.kubernetes.io/instance: {{ .Release.Name }}-mongo
