apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "websight-cms.fullname" . }}-mongo
  labels:
    app.kubernetes.io/name: {{ include "websight-cms.name" . }}-mongo
    app.kubernetes.io/instance: {{ .Release.Name }}-mongo
    app.kubernetes.io/version: {{ .Values.mongo.image.tag }}
    app.kubernetes.io/websight-version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: "content-store"
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "websight-cms.name" . }}-mongo
      app.kubernetes.io/instance: {{ .Release.Name }}-mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "websight-cms.name" . }}-mongo
        app.kubernetes.io/instance: {{ .Release.Name }}-mongo
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: mongoadmin
            - name: MONGO_INITDB_ROOT_USERNAME
              value: mongoadmin
          image: "{{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}"
          imagePullPolicy: {{ .Values.mongo.image.pullPolicy }}
          name: mongo
          ports:
            - containerPort: 27017
          resources:
            requests:
              memory: {{ .Values.mongo.resources.requests.memory }}
              cpu: {{ .Values.mongo.resources.requests.cpu }}
            limits:
              memory: {{ .Values.mongo.resources.limits.memory }}
              cpu: {{ .Values.mongo.resources.limits.cpu }}
          volumeMounts:
            - mountPath: /data/db
              name: mongo-repository
          {{- if .Values.mongo.livenessProbe.enabled }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.mongo.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.mongo.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.mongo.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.mongo.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.mongo.livenessProbe.successThreshold }}
            exec:
              command:
              - bash
              - "-c"
              - |
                mongo -u $MONGO_INITDB_ROOT_USERNAME -p $MONGO_INITDB_ROOT_PASSWORD --eval db.adminCommand\(\"ping\"\)
          {{- end }}
      restartPolicy: Always
      volumes:
        - name: mongo-repository
          persistentVolumeClaim:
            claimName: {{ include "websight-cms.fullname" . }}-mongo-repository
status: {}
