{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "websight-cms.fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- if gt .Values.cms.replicas 1 }}
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "websight-cms-sticky"
    nginx.ingress.kubernetes.io/session-cookie-expires: {{ .Values.cms.session.cookie.expires | quote }}
    nginx.ingress.kubernetes.io/session-cookie-max-age: {{ .Values.cms.session.cookie.maxAge | quote }}
    {{- end }}
    {{- if .Values.ingress.annotations }}
    {{- .Values.ingress.annotations | toYaml | nindent 4 }}
    {{- end }}
  labels:
    {{- include "websight-cms.labels" . | nindent 4 }}
spec:
  rules:
  - host: {{ tpl .Values.ingress.hosts.cms . }}
    http:
      paths:
      - pathType: ImplementationSpecific
        path: "/"
        backend:
          service:
            name: {{ include "websight-cms.fullname" . }}
            port:
              number: 8080 
{{- end }}