{{- if .Values.siteRepository.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "websight-cms.fullname" . }}-site-repository
  labels:
    app.kubernetes.io/name: {{ include "websight-cms.name" . }}-site-repository
    app.kubernetes.io/instance: {{ .Release.Name }}-site-repository
    app.kubernetes.io/websight-version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: "site-repository"
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
  {{- if .Values.siteRepository.rwxStorageClassName }}
    - ReadWriteMany
  storageClassName: {{ .Values.siteRepository.rwxStorageClassName }}
  {{ else }}
    - ReadWriteOnce
  {{ end -}}
  resources:
    requests:
      storage: {{ .Values.siteRepository.storage.size }}
{{- end }}