name: 'CI: verify chart'

permissions:
  id-token: write

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  verify-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: azure/setup-helm@v3
        with:
          version: v3.13.2

      - name: Test with template
        run: helm template --output-dir generated mycms websight-cms

      - name: Run chart helm-unittest
        run: |
          cd websight-cms
          helm plugin install https://github.com/helm-unittest/helm-unittest.git
          helm unittest -f 'tests/unit/*.yaml' .
